name: "Evaluation"
on:
  pull_request:
  push:
jobs:
  evaluate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: jlumbroso/free-disk-space@main
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix build --dry-run --file release.nix
    - run: nix flake check -L

# potential improvements:
#   - populate a Cachix cache with realtime kernels (speed/disk space)
#   - figure out the purpose of "nix build --dry-run --file release.nix"
